### ISSUE TITLE
Schedule comic updates

### ISSUE THREAD

**Issue by ryanvilbrandt** [ryanvilbrandt/comic_git#1]
Comic update should be able to run automatically, based on a time of day. The best (and only) way I can see how to do this is updating the cron settings on the GitHub Action.

Example:
```
on:
  push:
    branches:
      - master
  schedule:
    # Run at 12:00 on working days
    - cron: 0 12 * * 0-5
```

Not very new-user friendly, but what can you do?
